repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9 # Or latest ruff version
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format # Equivalent to black

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0 # Or latest isort version
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Or latest prettier version compatible with your prettier setup
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, html, yaml, markdown]
        args: [--write] # Tell prettier to fix files
